### ISSUE TITLE
how to use it and show us a demo

### ISSUE THREAD

**Issue by jianhuaixie** [ipfs-shipyard/cube#2]
could you show us a demo display your great working?

**Comment by victorb** [comment]
If you want to try to run it, you can either download the [latest release](https://github.com/ipfs-shipyard/cube/releases) or follow the instructs from the [contributing guide](https://github.com/ipfs-shipyard/cube/blob/master/docs/contributing.md).

I think it's a bit too early to produce any demonstration as the current functionality is limited.
